apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: resttemplateserver-sep
  newName: 210.90.24.172:8080/camit/raksmeychea/resttemplateserver-sep
  newTag: f19b37877b4983a8c393a2dbe91574c613fe51b9
